# close thymeleaf template cache default true.
spring:
  thymeleaf:
    cache: false

# open implant server for HTTPS
# first, use keytool tool of jdk make key store. eg: keytool -keystore mykeys.jks -genkey -alias tomcat -keyalg RAS.
# maybe hint 'Warning: JKS 密钥库使用专用格式。建议使用 "keytool -importkeystore -srckeystore mykeys.jks -destkeystore
# mykeys.jks -deststoretype pkcs12" 迁移到行业标准格式 PKCS12。', please ignore this, let`s continue.
server:
  port: 8443
  ssl:
    key-store: file:///Users/yangkaiqiang/Documents/java-workspace/mykeys.jks
    key-store-password: kqyang
    key-password: kqyang

# property file autowired.
amazon:
  associateId: kqyang0000

# use different properties for different environment, the public level is info.
logging:
  level:
    root: info
---
# for development, the log will appear on console, and log level is debug.
spring:
  profiles: development

logging:
  level:
    root: debug
---
# for production environment, the log will be write to logs file, and log level is warn
spring:
  profiles: production

logging:
  level:
    root: warn